package cn.education.web.model;

import java.util.Date;

public class TbChapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.id
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.chapter_no
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    private Short chapterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.class_id
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.url
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.create_time
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.id
     *
     * @return the value of tb_chapter.id
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.id
     *
     * @param id the value for tb_chapter.id
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.chapter_no
     *
     * @return the value of tb_chapter.chapter_no
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public Short getChapterNo() {
        return chapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.chapter_no
     *
     * @param chapterNo the value for tb_chapter.chapter_no
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public void setChapterNo(Short chapterNo) {
        this.chapterNo = chapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.class_id
     *
     * @return the value of tb_chapter.class_id
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.class_id
     *
     * @param classId the value for tb_chapter.class_id
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.url
     *
     * @return the value of tb_chapter.url
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.url
     *
     * @param url the value for tb_chapter.url
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.create_time
     *
     * @return the value of tb_chapter.create_time
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.create_time
     *
     * @param createTime the value for tb_chapter.create_time
     *
     * @mbggenerated Tue Feb 26 20:22:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}