package cn.education.web.model;

import cn.education.web.model.vo.CommentDto;

import javax.persistence.Transient;
import java.util.Date;
import java.util.List;

public class TbClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.id
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.class_name
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.class_desc
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private String classDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.lang_type
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private String langType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.image_url
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.total_score
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private Short totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.recommend
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private Byte recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.learn_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private Integer learnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.create_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_class.update_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    private Date updateTime;

    @Transient
    private List<TbChapter> chapters;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.id
     *
     * @return the value of tb_class.id
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.id
     *
     * @param id the value for tb_class.id
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.class_name
     *
     * @return the value of tb_class.class_name
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.class_name
     *
     * @param className the value for tb_class.class_name
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.class_desc
     *
     * @return the value of tb_class.class_desc
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public String getClassDesc() {
        return classDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.class_desc
     *
     * @param classDesc the value for tb_class.class_desc
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setClassDesc(String classDesc) {
        this.classDesc = classDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.lang_type
     *
     * @return the value of tb_class.lang_type
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public String getLangType() {
        return langType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.lang_type
     *
     * @param langType the value for tb_class.lang_type
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setLangType(String langType) {
        this.langType = langType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.image_url
     *
     * @return the value of tb_class.image_url
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.image_url
     *
     * @param imageUrl the value for tb_class.image_url
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.total_score
     *
     * @return the value of tb_class.total_score
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public Short getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.total_score
     *
     * @param totalScore the value for tb_class.total_score
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setTotalScore(Short totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.recommend
     *
     * @return the value of tb_class.recommend
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public Byte getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.recommend
     *
     * @param recommend the value for tb_class.recommend
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setRecommend(Byte recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.learn_time
     *
     * @return the value of tb_class.learn_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public Integer getLearnTime() {
        return learnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.learn_time
     *
     * @param learnTime the value for tb_class.learn_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setLearnTime(Integer learnTime) {
        this.learnTime = learnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.create_time
     *
     * @return the value of tb_class.create_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.create_time
     *
     * @param createTime the value for tb_class.create_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_class.update_time
     *
     * @return the value of tb_class.update_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_class.update_time
     *
     * @param updateTime the value for tb_class.update_time
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public List<TbChapter> getChapters() {
        return chapters;
    }

    public void setChapters(List<TbChapter> chapters) {
        this.chapters = chapters;
    }
}