package cn.education.web.model;

import java.util.Date;

public class TbComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.class_id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.user_id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.content
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.create_time
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.id
     *
     * @return the value of tb_comment.id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.id
     *
     * @param id the value for tb_comment.id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.class_id
     *
     * @return the value of tb_comment.class_id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.class_id
     *
     * @param classId the value for tb_comment.class_id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.user_id
     *
     * @return the value of tb_comment.user_id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.user_id
     *
     * @param userId the value for tb_comment.user_id
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.content
     *
     * @return the value of tb_comment.content
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.content
     *
     * @param content the value for tb_comment.content
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.create_time
     *
     * @return the value of tb_comment.create_time
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.create_time
     *
     * @param createTime the value for tb_comment.create_time
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}