package cn.education.web.model;

import java.util.Date;

public class TbFavorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_favorite.id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_favorite.user_id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_favorite.class_id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_favorite.create_time
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_favorite.id
     *
     * @return the value of tb_favorite.id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_favorite.id
     *
     * @param id the value for tb_favorite.id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_favorite.user_id
     *
     * @return the value of tb_favorite.user_id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_favorite.user_id
     *
     * @param userId the value for tb_favorite.user_id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_favorite.class_id
     *
     * @return the value of tb_favorite.class_id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_favorite.class_id
     *
     * @param classId the value for tb_favorite.class_id
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_favorite.create_time
     *
     * @return the value of tb_favorite.create_time
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_favorite.create_time
     *
     * @param createTime the value for tb_favorite.create_time
     *
     * @mbggenerated Mon Mar 04 20:07:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}