package cn.education.web.model;

import java.util.Date;

public class TbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.wx_no
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private String wxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.wx_name
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private String wxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.wx_avator
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private String wxAvator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.role
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private Byte role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.score
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private Short score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.create_time
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.update_time
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.wx_no
     *
     * @return the value of tb_user.wx_no
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public String getWxNo() {
        return wxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.wx_no
     *
     * @param wxNo the value for tb_user.wx_no
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setWxNo(String wxNo) {
        this.wxNo = wxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.wx_name
     *
     * @return the value of tb_user.wx_name
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.wx_name
     *
     * @param wxName the value for tb_user.wx_name
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setWxName(String wxName) {
        this.wxName = wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.wx_avator
     *
     * @return the value of tb_user.wx_avator
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public String getWxAvator() {
        return wxAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.wx_avator
     *
     * @param wxAvator the value for tb_user.wx_avator
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setWxAvator(String wxAvator) {
        this.wxAvator = wxAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role
     *
     * @return the value of tb_user.role
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public Byte getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role
     *
     * @param role the value for tb_user.role
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setRole(Byte role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.score
     *
     * @return the value of tb_user.score
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public Short getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.score
     *
     * @param score the value for tb_user.score
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setScore(Short score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.create_time
     *
     * @return the value of tb_user.create_time
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.create_time
     *
     * @param createTime the value for tb_user.create_time
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.update_time
     *
     * @return the value of tb_user.update_time
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.update_time
     *
     * @param updateTime the value for tb_user.update_time
     *
     * @mbggenerated Sun Mar 03 17:54:49 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}