package cn.education.web.mapper;

import cn.education.web.model.TbClass;
import cn.education.web.model.TbClassExample;
import java.util.List;

import cn.education.web.model.dto.QueryClassDto;
import cn.education.web.model.vo.ClassDetail;
import cn.education.web.model.vo.ClassInstance;
import org.apache.ibatis.annotations.Param;

public interface TbClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int countByExample(TbClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int deleteByExample(TbClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int insert(TbClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int insertSelective(TbClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    List<TbClass> selectByExample(TbClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    TbClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbClass record, @Param("example") TbClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int updateByExample(@Param("record") TbClass record, @Param("example") TbClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int updateByPrimaryKeySelective(TbClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_class
     *
     * @mbggenerated Mon Mar 04 11:12:21 CST 2019
     */
    int updateByPrimaryKey(TbClass record);

    List<ClassInstance> queryClass(QueryClassDto queryClassDto);

    List<ClassInstance> queryCurrentLearnRecord(Integer userId);

    ClassDetail getDetailById(Integer classId);

    List<ClassInstance> queryFavoriteClass(Integer id);

    void conversionClass(@Param("classId") Integer classId, @Param("userId")Integer userId);

    List<ClassInstance> getConversionClass(QueryClassDto queryClassDto);

    void commitLearn(Integer classId);
}