package cn.education.web.mapper;

import cn.education.web.model.TbComment;
import cn.education.web.model.TbCommentExample;
import java.util.List;

import cn.education.web.model.vo.CommentDto;
import org.apache.ibatis.annotations.Param;

public interface TbCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int countByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int deleteByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int insert(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int insertSelective(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    List<TbComment> selectByExample(TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    TbComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbComment record, @Param("example") TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int updateByExample(@Param("record") TbComment record, @Param("example") TbCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int updateByPrimaryKeySelective(TbComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment
     *
     * @mbggenerated Tue Feb 26 20:24:07 CST 2019
     */
    int updateByPrimaryKey(TbComment record);

    List<CommentDto> getCommentByClassId(Integer classId);
}