package cn.education.web.mapper;

import cn.education.web.model.TbLearnRecord;
import cn.education.web.model.TbLearnRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLearnRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int countByExample(TbLearnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int deleteByExample(TbLearnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int insert(TbLearnRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int insertSelective(TbLearnRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    List<TbLearnRecord> selectByExample(TbLearnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    TbLearnRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbLearnRecord record, @Param("example") TbLearnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int updateByExample(@Param("record") TbLearnRecord record, @Param("example") TbLearnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int updateByPrimaryKeySelective(TbLearnRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_learn_record
     *
     * @mbggenerated Tue Feb 26 20:24:56 CST 2019
     */
    int updateByPrimaryKey(TbLearnRecord record);
}