package cn.education.web.mapper;

import cn.education.web.model.TbPurchase;
import cn.education.web.model.TbPurchaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int countByExample(TbPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int deleteByExample(TbPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int insert(TbPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int insertSelective(TbPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    List<TbPurchase> selectByExample(TbPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    TbPurchase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbPurchase record, @Param("example") TbPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int updateByExample(@Param("record") TbPurchase record, @Param("example") TbPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(TbPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_purchase
     *
     * @mbggenerated Tue Feb 26 20:25:15 CST 2019
     */
    int updateByPrimaryKey(TbPurchase record);
}